# Generated by Django 5.2.16 on 2026-07-14 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã vấn đề sức khỏe')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tên vấn đề sức khỏe')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Vấn đề sức khỏe',
                'verbose_name_plural': 'Các vấn đề sức khỏe',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('user', 'Người dùng')], db_index=True, default='user', max_length=20, verbose_name='Vai trò'),
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Tuổi')),
                ('weight', models.FloatField(help_text='Đơn vị: kilogram (kg)', validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Cân nặng')),
                ('height', models.FloatField(help_text='Đơn vị: centimet (cm)', validators=[django.core.validators.MinValueValidator(30.0)], verbose_name='Chiều cao')),
                ('bmi', models.FloatField(blank=True, editable=False, null=True, verbose_name='Chỉ số BMI')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Ít vận động'), ('light', 'Vận động nhẹ'), ('moderate', 'Vận động vừa'), ('active', 'Vận động nhiều'), ('very_active', 'Vận động rất nhiều')], default='moderate', max_length=20, verbose_name='Mức độ vận động')),
                ('goal', models.CharField(choices=[('lose_weight', 'Giảm cân'), ('maintain_weight', 'Duy trì cân nặng'), ('gain_weight', 'Tăng cân')], default='maintain_weight', max_length=20, verbose_name='Mục tiêu')),
                ('target_weight', models.FloatField(blank=True, help_text='Đơn vị: kilogram (kg)', null=True, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Cân nặng mục tiêu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ sức khỏe',
                'verbose_name_plural': 'Hồ sơ sức khỏe',
            },
        ),
        migrations.CreateModel(
            name='UserHealthIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('diagnosed_date', models.DateField(blank=True, null=True, verbose_name='Ngày chẩn đoán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('health_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_users', to='healthplanapp.healthissue', verbose_name='Vấn đề sức khỏe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_issues', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Vấn đề sức khỏe của người dùng',
                'verbose_name_plural': 'Các vấn đề sức khỏe của người dùng',
                'constraints': [models.UniqueConstraint(fields=('user', 'health_issue'), name='unique_user_health_issue')],
            },
        ),
    ]
