# Generated by Django 5.2.16 on 2026-07-14 10:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0002_healthissue_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name_vi', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('user_group', models.CharField(choices=[('adult', 'Người trưởng thành'), ('older_adult', 'Người cao tuổi'), ('wheelchair', 'Người dùng xe lăn')], max_length=20)),
                ('met_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name_vi', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_vi', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutrientHealthRiskRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('rule_type', models.CharField(choices=[('minimum', 'Tối thiểu'), ('maximum', 'Tối đa'), ('limit', 'Hạn chế'), ('avoid', 'Nên tránh'), ('encourage', 'Khuyến khích')], max_length=20)),
                ('minimum_value', models.FloatField(blank=True, null=True)),
                ('maximum_value', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True)),
                ('health_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_rules', to='healthplanapp.healthissue')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_rules', to='healthplanapp.nutrient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('amount_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='healthplanapp.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='healthplanapp.nutrient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food', 'nutrient'), name='unique_food_nutrient')],
            },
        ),
    ]
