# Generated by Django 5.2.16 on 2026-07-14 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0003_exerciseactivity_food_nutrient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrienthealthriskrule',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='healthplanapp.nutrient'),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nutrienthealthriskrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nutrienthealthriskrule',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_rules', to='healthplanapp.nutrient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
