# Generated by Django 5.2.16 on 2026-07-14 11:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0004_nutrienthealthriskrule_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthissue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='healthprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='userhealthissue',
            options={},
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='bmi',
        ),
        migrations.AddField(
            model_name='exerciseactivity',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='met_value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Ít vận động'), ('light', 'Vận động nhẹ'), ('moderate', 'Vận động vừa'), ('active', 'Vận động nhiều'), ('very_active', 'Vận động rất nhiều')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Giảm cân'), ('maintain_weight', 'Duy trì cân nặng'), ('gain_weight', 'Tăng cân')], default='maintain_weight', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nutrienthealthriskrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nutrienthealthriskrule',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nutrienthealthriskrule',
            name='maximum_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nutrienthealthriskrule',
            name='minimum_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nutrienthealthriskrule',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('user', 'Người dùng')], db_index=True, default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='diagnosed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='health_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_users', to='healthplanapp.healthissue'),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userhealthissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='nutrienthealthriskrule',
            constraint=models.UniqueConstraint(fields=('health_issue', 'nutrient', 'rule_type'), name='unique_nutrient_health_rule'),
        ),
    ]
