# Generated by Django 5.2.16 on 2026-08-06 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "healthplanapp",
            "0005_alter_healthissue_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "specialization",
                    models.CharField(max_length=150),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "title",
                    models.CharField(max_length=255),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("meal", "Kế hoạch ăn uống"),
                            ("exercise", "Kế hoạch luyện tập"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(),
                ),
                (
                    "start_date",
                    models.DateField(),
                ),
                (
                    "end_date",
                    models.DateField(),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),

        # Xóa các bảng phụ thuộc trước.
        migrations.DeleteModel(
            name="FoodNutrient",
        ),
        migrations.DeleteModel(
            name="NutrientHealthRiskRule",
        ),
        migrations.DeleteModel(
            name="UserHealthIssue",
        ),

        # Sau đó mới xóa các bảng chính.
        migrations.DeleteModel(
            name="ExerciseActivity",
        ),
        migrations.DeleteModel(
            name="Food",
        ),
        migrations.DeleteModel(
            name="Nutrient",
        ),

        migrations.AddField(
            model_name="healthprofile",
            name="health_issues",
            field=models.ManyToManyField(
                blank=True,
                related_name="health_profiles",
                to="healthplanapp.healthissue",
            ),
        ),
        migrations.AlterField(
            model_name="healthissue",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthissue",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Khách hàng"),
                    ("expert", "Chuyên gia"),
                    ("admin", "Quản trị viên"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expert_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_experts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="healthplan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="healthplan",
            name="expert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_health_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]