# Generated by Django 5.2.16 on 2026-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0006_expertprofile_healthplan_delete_exerciseactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='other_health_issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
