# Generated by Django 5.2.16 on 2026-08-07 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0007_healthprofile_other_health_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthissue',
            name='kind',
            field=models.CharField(choices=[('disease', 'Nhóm bệnh'), ('type', 'Loại bệnh'), ('stage', 'Giai đoạn')], default='disease', max_length=20),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='healthplanapp.healthissue'),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='healthissue',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
