# Generated by Django 5.2.16 on 2026-08-11 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0009_consultationsession_consultationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('food_id', models.CharField(max_length=20, unique=True)),
                ('source_name', models.CharField(max_length=50)),
                ('name_vi', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('category_vi', models.CharField(max_length=100)),
                ('category_en', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('raw_ingredient', 'Nguyên liệu thô'), ('cooked_food', 'Thực phẩm đã nấu'), ('basic_food', 'Thực phẩm cơ bản'), ('beverage', 'Đồ uống'), ('prepared_food', 'Thực phẩm chế biến sẵn')], max_length=30)),
                ('processing_level', models.CharField(choices=[('unprocessed', 'Chưa chế biến'), ('minimally_processed', 'Chế biến tối thiểu'), ('processed', 'Đã chế biến')], max_length=30)),
                ('kcal_per_100g', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_g', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('carb_g', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('potassium_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
