# Generated by Django 5.2.16 on 2026-08-11 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0010_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Bữa sáng'), ('lunch', 'Bữa trưa'), ('dinner', 'Bữa tối')], max_length=20)),
                ('health_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='healthplanapp.healthplan')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('serving_grams', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='healthplanapp.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='healthplanapp.meal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('health_plan', 'date', 'meal_type'), name='unique_meal_per_plan_date_type'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.UniqueConstraint(fields=('meal', 'food'), name='unique_food_per_meal'),
        ),
    ]
