# Generated by Django 5.2.16 on 2026-08-11 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0011_meal_mealitem_meal_unique_meal_per_plan_date_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthConditionNutrientRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('condition_code', models.CharField(db_index=True, max_length=100)),
                ('evaluation_field', models.CharField(max_length=50)),
                ('rule_type', models.CharField(choices=[('avoid', 'Tránh'), ('individualize', 'Cá nhân hóa'), ('limit', 'Hạn chế'), ('moderate', 'Điều chỉnh'), ('monitor', 'Theo dõi'), ('prioritize', 'Ưu tiên')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'Cao'), ('medium', 'Trung bình'), ('low', 'Thấp')], max_length=10)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('threshold_unit', models.CharField(blank=True, default='', max_length=50)),
                ('applies_when', models.CharField(blank=True, default='', max_length=100)),
                ('recommendation_vi', models.TextField()),
                ('clinical_caution_vi', models.TextField(blank=True, default='')),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
