# Generated by Django 5.2.16 on 2026-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0012_healthconditionnutrientrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal_role',
            field=models.CharField(choices=[('carbohydrate', 'Tinh bột'), ('protein', 'Chất đạm'), ('vegetable', 'Rau củ'), ('breakfast_side', 'Thực phẩm phụ buổi sáng'), ('other', 'Khác')], default='other', max_length=30),
        ),
    ]
