# Generated by Django 5.2.16 on 2026-08-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanapp', '0013_food_meal_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_meal_suitable',
            field=models.BooleanField(default=False),
        ),
    ]
