import { Platform, StyleSheet } from "react-native";

import { Colors, Radius, Shadow, Spacing } from "../../configs/Theme";

export default StyleSheet.create({
    header: {padding: Spacing.medium, paddingBottom: 12},
    titleRow: {flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between"},
    titleBlock: {flex: 1, paddingRight: 12},
    title: {fontSize: 27, lineHeight: 34, fontWeight: "800", color: Colors.text},
    subtitle: {marginTop: 5, fontSize: 14, lineHeight: 20, color: Colors.textSecondary},
    newButton: {width: 46, height: 46, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primary},
    list: {paddingHorizontal: Spacing.medium, paddingBottom: 110},
    sessionCard: {marginBottom: 11, padding: 14, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.medium, backgroundColor: Colors.surface, ...Shadow},
    sessionIcon: {width: 44, height: 44, marginRight: 11, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primaryLight},
    sessionMain: {flex: 1},
    sessionTitle: {fontSize: 15, lineHeight: 20, fontWeight: "800", color: Colors.text},
    sessionDate: {marginTop: 4, fontSize: 12, color: Colors.textSecondary},
    iconButton: {width: 38, height: 38, alignItems: "center", justifyContent: "center"},
    modalOverlay: {flex: 1, padding: Spacing.medium, alignItems: "center", justifyContent: "center", backgroundColor: Colors.overlay},
    modal: {width: "100%", maxWidth: 390, padding: Spacing.large, borderRadius: Radius.large, backgroundColor: Colors.surface},
    modalTitle: {fontSize: 20, fontWeight: "800", color: Colors.text},
    modalDescription: {marginTop: 6, marginBottom: Spacing.medium, fontSize: 14, lineHeight: 20, color: Colors.textSecondary},
    modalActions: {flexDirection: "row"},
    modalButton: {flex: 1, marginHorizontal: 4},
    chat: {flex: 1},
    messageList: {paddingHorizontal: 12, paddingTop: Spacing.medium, paddingBottom: 12},
    emptyChat: {paddingHorizontal: Spacing.large, paddingTop: 80, alignItems: "center"},
    emptyIcon: {width: 72, height: 72, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primaryLight},
    emptyTitle: {marginTop: Spacing.medium, fontSize: 20, fontWeight: "800", textAlign: "center", color: Colors.text},
    emptyText: {marginTop: 7, fontSize: 14, lineHeight: 21, textAlign: "center", color: Colors.textSecondary},
    messageRow: {marginBottom: 10, flexDirection: "row"},
    userRow: {justifyContent: "flex-end"},
    assistantRow: {justifyContent: "flex-start"},
    bubble: {maxWidth: "82%", paddingHorizontal: 14, paddingVertical: 11, borderRadius: 17},
    userBubble: {borderBottomRightRadius: 5, backgroundColor: Colors.primary},
    assistantBubble: {borderBottomLeftRadius: 5, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.surface},
    messageText: {fontSize: 15, lineHeight: 22},
    userText: {color: Colors.surface},
    assistantText: {color: Colors.text},
    waitingBubble: {paddingHorizontal: 17, paddingVertical: 14},
    composerArea: {paddingHorizontal: 10, paddingTop: 8, borderTopWidth: 1, borderTopColor: Colors.border, backgroundColor: Colors.surface},
    chatError: {marginBottom: 7, paddingHorizontal: 10, fontSize: 12, lineHeight: 17, color: Colors.error},
    composer: {flexDirection: "row", alignItems: "flex-end"},
    inputBox: {flex: 1, minHeight: 48, maxHeight: 120, paddingHorizontal: 14, paddingVertical: Platform.OS === "ios" ? 13 : 9, borderWidth: 1, borderColor: Colors.border, borderRadius: 18, fontSize: 15, color: Colors.text, backgroundColor: Colors.background},
    sendButton: {width: 48, height: 48, marginLeft: 8, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primary},
    disabledSend: {backgroundColor: Colors.disabled},
    safetyText: {paddingVertical: 7, fontSize: 10, textAlign: "center", color: Colors.textSecondary}
});
