import { StyleSheet } from "react-native";

import { Colors, Radius, Shadow, Spacing } from "../../configs/Theme";

export default StyleSheet.create({
    listHeader: {paddingHorizontal: Spacing.medium, paddingTop: Spacing.medium, paddingBottom: 12},
    titleRow: {flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between"},
    titleBlock: {flex: 1, paddingRight: 12},
    title: {fontSize: 27, lineHeight: 34, fontWeight: "800", color: Colors.text},
    subtitle: {marginTop: 5, fontSize: 14, lineHeight: 20, color: Colors.textSecondary},
    createButton: {width: 46, height: 46, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primary},
    listContent: {paddingHorizontal: Spacing.medium, paddingBottom: 110},
    planCard: {marginBottom: 12, padding: Spacing.medium, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.medium, backgroundColor: Colors.surface, ...Shadow},
    planTop: {flexDirection: "row", alignItems: "flex-start"},
    dateBox: {width: 54, height: 54, marginRight: 12, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primaryLight},
    dateDay: {fontSize: 18, fontWeight: "800", color: Colors.primaryDark},
    dateMonth: {fontSize: 10, fontWeight: "700", color: Colors.primary},
    planMain: {flex: 1},
    planTitle: {fontSize: 16, lineHeight: 22, fontWeight: "800", color: Colors.text},
    planDate: {marginTop: 4, fontSize: 12, color: Colors.textSecondary},
    planBottom: {marginTop: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between"},
    mealCount: {fontSize: 12, color: Colors.textSecondary},
    formScroll: {padding: Spacing.medium, paddingBottom: Spacing.huge},
    formIntro: {marginBottom: Spacing.large},
    formTitle: {fontSize: 25, lineHeight: 32, fontWeight: "800", color: Colors.text},
    formDescription: {marginTop: 7, fontSize: 14, lineHeight: 21, color: Colors.textSecondary},
    errorBox: {marginBottom: Spacing.medium, padding: 12, borderRadius: Radius.small, backgroundColor: "#FFF0F0"},
    errorText: {fontSize: 14, lineHeight: 20, color: Colors.error},
    formCard: {marginBottom: Spacing.medium},
    noteBox: {marginBottom: Spacing.large, padding: 12, flexDirection: "row", borderRadius: Radius.small, backgroundColor: Colors.primaryLight},
    noteText: {flex: 1, marginLeft: 8, fontSize: 13, lineHeight: 19, color: Colors.primaryDark},
    detailContent: {padding: Spacing.medium, paddingBottom: Spacing.huge},
    detailHeader: {marginBottom: Spacing.medium, padding: Spacing.large, borderRadius: Radius.large, backgroundColor: Colors.primary},
    detailDate: {fontSize: 13, fontWeight: "700", color: "#D8F0E4"},
    detailTitle: {marginTop: 6, fontSize: 23, lineHeight: 30, fontWeight: "800", color: Colors.surface},
    badges: {marginTop: 12, flexDirection: "row", flexWrap: "wrap", gap: 7},
    statusInfo: {marginBottom: Spacing.medium, padding: 12, flexDirection: "row", borderRadius: Radius.medium, backgroundColor: "#FFF8E9"},
    statusText: {flex: 1, marginLeft: 8, fontSize: 13, lineHeight: 19, color: "#815B1C"},
    mealCard: {marginBottom: Spacing.medium},
    mealHeader: {marginBottom: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between"},
    mealTitle: {fontSize: 17, fontWeight: "800", color: Colors.text},
    mealCalories: {fontSize: 12, fontWeight: "700", color: Colors.primary},
    foodRow: {paddingVertical: 11, flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: Colors.border},
    foodIcon: {width: 36, height: 36, marginRight: 10, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: Colors.background},
    foodMain: {flex: 1},
    foodName: {fontSize: 14, fontWeight: "700", color: Colors.text},
    foodServing: {marginTop: 3, fontSize: 12, color: Colors.textSecondary},
    foodCalories: {fontSize: 13, fontWeight: "700", color: Colors.text},
    reviewNote: {fontSize: 14, lineHeight: 21, color: Colors.textSecondary},
    deleteButton: {marginTop: Spacing.small}
});
