from pathlib import Path

Path_Root = Path(__file__).resolve().parents[1]

VECTOR_PATH = f"{Path_Root}/storage/chroma"
MODEL_NAME = "BAAI/bge-m3"

OLLAMA_MODEL_NAME = "qwen2.5:7b"
OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_TEMPERATURE = 0.2

COLLECTION_NAME = "health_knowledge"
EMBEDDING_BATCH_SIZE = 16
TOP_N = 10
TOP_K = 4
MIN_SIMILARITY = 0.4

CONDITION_ROUTER_COLLECTION_NAME = "condition_router"
ROUTER_TOP_N = 5
ROUTER_MIN_SIMILARITY = 0.70
ROUTER_MIN_SCORE_GAP = 0.05
ROUTER_MAX_MATCHES_PER_CONDITION = 3

BM25_K1 = 1.5
BM25_B = 0.75
BM25_TOP_N = 10
BM25_MAX_NGRAM = 3

HYBRID_DENSE_TOP_N = 10
HYBRID_BM25_TOP_N = 10
HYBRID_FINAL_TOP_N = 10
RRF_K = 60

HYBRID_MATCH_WEIGHTS = (1.0, 0.5, 0.25)
HYBRID_CONSENSUS_MIN_SIMILARITY = 0.55
HYBRID_CONSENSUS_MAX_BM25_RANK = 5