import { StyleSheet } from "react-native";

import { Colors, Radius, Shadow, Spacing } from "../../configs/Theme";

export default StyleSheet.create({
    header: {padding: Spacing.medium, paddingBottom: 10},
    title: {fontSize: 27, lineHeight: 34, fontWeight: "800", color: Colors.text},
    subtitle: {marginTop: 5, fontSize: 14, lineHeight: 20, color: Colors.textSecondary},
    searchRow: {marginTop: Spacing.medium, flexDirection: "row", alignItems: "center"},
    searchBox: {flex: 1, minHeight: 48, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.medium, backgroundColor: Colors.surface},
    searchInput: {flex: 1, marginLeft: 8, paddingVertical: 10, fontSize: 15, color: Colors.text},
    filterButton: {width: 48, height: 48, marginLeft: 8, borderRadius: Radius.medium, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primary},
    filters: {marginTop: 10, padding: 12, borderRadius: Radius.medium, backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border},
    filterLabel: {marginBottom: 7, fontSize: 13, fontWeight: "700", color: Colors.text},
    filterActions: {flexDirection: "row"},
    filterAction: {flex: 1, minHeight: 44, marginHorizontal: 4},
    inlineError: {marginTop: 10, padding: 11, borderRadius: Radius.small, backgroundColor: "#FFF0F0"},
    inlineErrorText: {fontSize: 12, lineHeight: 18, color: Colors.error},
    retryText: {marginTop: 5, fontSize: 12, fontWeight: "700", color: Colors.primary},
    resultText: {marginTop: 10, fontSize: 12, color: Colors.textSecondary},
    list: {paddingHorizontal: Spacing.medium, paddingBottom: 110},
    foodCard: {marginBottom: 11, padding: 14, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.medium, backgroundColor: Colors.surface, ...Shadow},
    foodTop: {flexDirection: "row", alignItems: "center"},
    foodIcon: {width: 46, height: 46, marginRight: 12, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: Colors.primaryLight},
    foodMain: {flex: 1},
    foodName: {fontSize: 15, lineHeight: 21, fontWeight: "800", color: Colors.text},
    foodEnglish: {marginTop: 2, fontSize: 12, color: Colors.textSecondary},
    category: {marginTop: 8, alignSelf: "flex-start", paddingHorizontal: 9, paddingVertical: 4, borderRadius: Radius.round, backgroundColor: Colors.background, fontSize: 11, color: Colors.textSecondary},
    nutrients: {marginTop: 11, paddingTop: 10, flexDirection: "row", borderTopWidth: 1, borderTopColor: Colors.border},
    nutrient: {flex: 1, alignItems: "center"},
    nutrientValue: {fontSize: 13, fontWeight: "800", color: Colors.text},
    nutrientLabel: {marginTop: 2, fontSize: 10, color: Colors.textSecondary},
    footer: {paddingVertical: Spacing.large},
    loadMoreError: {paddingVertical: Spacing.medium, alignItems: "center"},
    detailContent: {padding: Spacing.medium, paddingBottom: Spacing.huge},
    detailHero: {marginBottom: Spacing.medium, padding: Spacing.large, borderRadius: Radius.large, backgroundColor: Colors.primary},
    heroIcon: {width: 58, height: 58, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.18)"},
    detailName: {marginTop: 14, fontSize: 24, lineHeight: 31, fontWeight: "800", color: Colors.surface},
    detailEnglish: {marginTop: 5, fontSize: 14, color: "#D8F0E4"},
    detailMeta: {marginTop: 12, flexDirection: "row", flexWrap: "wrap"},
    metaChip: {marginRight: 7, marginBottom: 7, paddingHorizontal: 10, paddingVertical: 6, borderRadius: Radius.round, backgroundColor: "rgba(255,255,255,0.16)"},
    metaText: {fontSize: 11, fontWeight: "700", color: Colors.surface},
    nutritionCard: {marginBottom: Spacing.medium},
    nutritionRow: {paddingVertical: 11, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: Colors.border},
    nutritionName: {flex: 1, fontSize: 14, color: Colors.textSecondary},
    nutritionValue: {fontSize: 14, fontWeight: "800", color: Colors.text},
    sourceText: {fontSize: 13, lineHeight: 19, color: Colors.textSecondary}
});
