name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    defaults:
      run:
        working-directory: HealthyPlan/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          CLIENT_ID: gAHhEM0x5gtBfvttIjhVnvpCn7qmRLMPNZy68mRH
          CLIENT_SECRET: oaNeWtIZ9WJjPnNX21vVCLeNLZIosOVrO25OlpgVkiunieJKtZknVEiCuv1eAhCIVpZEwJKghZFbz96pLaXKHz8XDN1xygg0Wsu7krZhJYi8Iy8onimOfmL4Negf4Dq0
        run: |
          python manage.py test
